[package]
name = "falling"
version = "0.0.1"
edition = "2024"

[dependencies]
bevy = { version = "0.16.*", features = [ "bevy_dev_tools" ]}
bevy_rapier2d =  { version = "0.31.*", features = [ "simd-stable", "debug-render-2d" ] }