name: Rust Release Build

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always
  BIN_NAME: falling

jobs:
  build:
    name: Build on ${{ matrix.os }} (${{ matrix.target }})
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux
          - os: ubuntu-latest
            runs-on: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            out: falling-x86_64-linux
          - os: ubuntu-latest
            runs-on: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
            out: falling-aarch64-linux

          # macOS
          - os: macos-latest
            runs-on: macos-latest
            target: x86_64-apple-darwin
            out: falling-x86_64-macos
          - os: macos-latest
            runs-on: macos-latest
            target: aarch64-apple-darwin
            out: falling-aarch64-macos

          # Windows
          - os: windows-latest
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc
            out: falling-x86_64.exe
          - os: windows-latest
            runs-on: windows-latest
            target: aarch64-pc-windows-msvc
            out: falling-aarch64.exe

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        if: startsWith(matrix.target, 'x86_64-unknown-linux') || startsWith(matrix.target, 'aarch64-unknown-linux')
        run: sudo apt-get update && sudo apt-get install -y pkg-config libasound2-dev

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Rename binary
        shell: bash
        run: |
          mkdir -p dist
          src="target/${{ matrix.target }}/release/${{ env.BIN_NAME }}"
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            mv "${src}.exe" "dist/${{ matrix.out }}"
          else
            mv "${src}" "dist/${{ matrix.out }}"
          fi

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.out }}
          path: dist/${{ matrix.out }}

  freebsd:
    name: Build on FreeBSD (${{ matrix.arch }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            release: "15.0"
            target: x86_64-unknown-freebsd
            out: falling-x86_64-freebsd
          - arch: aarch64
            release: "15.0"
            target: aarch64-unknown-freebsd
            out: falling-aarch64-freebsd

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build inside FreeBSD VM
        uses: vmactions/freebsd-vm@v1
        with:
          release: ${{ matrix.release }}
          arch: ${{ matrix.arch }}
          usesh: true
          mem: 4096
          prepare: |
            pkg install -y curl git
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            . $HOME/.cargo/env
          run: |
            . $HOME/.cargo/env
            rustc --version
            cargo --version
            cargo build --release --target ${{ matrix.target }}
            mkdir -p dist
            mv target/${{ matrix.target }}/release/falling dist/${{ matrix.out }}

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.out }}
          path: dist/${{ matrix.out }}

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build, freebsd]
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
